steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=gcloud_prod.json.enc
      - --plaintext-file=gcloud.json
      - --location=us-central1
      - --keyring=logflare-prod-keyring-us-central1
      - --key=logflare-prod-secrets-key
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./config/prod.secret.exs.enc
      - --plaintext-file=./config/prod.secret.exs
      - --location=us-central1
      - --keyring=logflare-prod-keyring-us-central1
      - --key=logflare-prod-secrets-key
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/logflare-232118/logflare_app:$COMMIT_SHA",
        "-t",
        "gcr.io/logflare-232118/logflare_app:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/logflare-232118/logflare_app:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - set
      - image
      - deployment/logflare-prod
      - logflare=gcr.io/logflare-232118/logflare_app:$COMMIT_SHA
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1-a
      - CLOUDSDK_CONTAINER_CLUSTER=logflare-prod-regional-cluster

timeout: 1800s
