version: "3.9"
services:
  db:
    image: postgres:13.4
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

volumes:
  pg-data: