apiVersion: apps/v1
kind: Deployment
metadata:
  name: logflare-staging
  labels:
    app: logflare-staging
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: logflare-staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logflare-staging
    spec:
      containers:
        - image: gcr.io/logflare-staging/logflare_origin:latest
          imagePullPolicy: Always
          name: logflare
          ports:
            - containerPort: 4000
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 120
