name: Check pages build

on:
  pull_request:
    branches: ["staging"]
    paths:
      - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: ">=16.14"
          cache: npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          cache-dependency-path: docs/docs.logflare.com/package-lock.json
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Restore cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-primes
          path: |
            docs/docs.logflare.com/node_modules
      - name: Install dependencies
        working-directory: ./docs/docs.logflare.com
        run: npm ci
      - name: Check build
        working-directory: ./docs/docs.logflare.com
        run: npm run build
